PETSCPRESSURE_OPTIONS = {
    "ksp_type": "cg",
    "pc_type": "gamg",
    "norm_type": "unpreconditioned",
    "rtol": 0.0,
    "atol": 1.0e-8,
    "max_it": 400,
    "monitor": True,
    "monitor_stdout": False,
    "pc_gamg_type": "agg",
    "pc_gamg_agg_nsmooths": 1,
    "pc_gamg_square_graph": 1,
    "pc_gamg_threshold": 0.02,
    "mg_levels_ksp_type": "richardson",
    "mg_levels_pc_type": "sor",
    "mg_levels_ksp_max_it": 3,
    "mg_coarse_ksp_type": "preonly",
    "mg_coarse_pc_type": "svd",
}
